eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server

#链路追踪的数据存入elasticsearch
zipkin:
  storage:
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: localhost:9200
      index: zipkin
      index-replicas: 1
      index-shards: 5
    type: elasticsearch
management:
  metrics:
    web:
      server:
        auto-time-requests: false

